export const NUM_MONTHS = 6;

export const eventTypeTexts = {
	meeting: 'Meeting with an Expert',
	qa: 'Question-answer',
	conference: 'Conference',
	webinar: 'Webinar',
};

export const mockEvents = [
	{
		id: 1,
		title: 'Team Meeting',
		description: 'Discuss project progress.',
		date: '2024-10-31',
		time: '10:00',
		location: 'Conference Room A',
		type: 'meeting',
	},
	{
		id: 2,
		title: 'QA Review',
		description: 'Review QA processes and outcomes.',
		date: '2024-11-01',
		time: '14:00',
		location: 'Zoom',
		type: 'qa',
	},
	{
		id: 3,
		title: 'Monthly Conference',
		description: 'Discuss monthly results and metrics.',
		date: '2024-11-05',
		time: '09:00',
		location: 'Main Hall',
		type: 'conference',
	},
	{
		id: 4,
		title: 'Webinar on React',
		description: 'Learn about the latest in React development.',
		date: '2024-11-10',
		time: '11:00',
		location: 'Online',
		type: 'webinar',
	},
	{
		id: 5,
		title: 'Project Kickoff',
		description: 'Kickoff meeting for the new project.',
		date: '2024-11-15',
		time: '13:00',
		location: 'Room 201',
		type: 'meeting',
	},
	{
		id: 6,
		title: 'QA Testing',
		description: 'Perform tests on the latest build.',
		date: '2024-11-20',
		time: '15:00',
		location: 'Lab',
		type: 'qa',
	},
	{
		id: 7,
		title: 'Team Lunch',
		description: 'Casual lunch with the team.',
		date: '2024-11-25',
		time: '12:00',
		location: 'Cafeteria',
		type: 'meeting',
	},
	{
		id: 8,
		title: 'Conference on AI',
		description: 'Annual conference on AI advancements.',
		date: '2024-12-01',
		time: '09:00',
		location: 'Convention Center',
		type: 'conference',
	},
	{
		id: 9,
		title: 'Webinar: UX Design',
		description: 'Understanding user experience in design.',
		date: '2024-12-05',
		time: '16:00',
		location: 'Online',
		type: 'webinar',
	},
	{
		id: 10,
		title: 'Sprint Review',
		description: 'Review sprint outcomes with stakeholders.',
		date: '2024-12-10',
		time: '10:00',
		location: 'Room 102',
		type: 'meeting',
	},
	{
		id: 11,
		title: 'Holiday Party',
		description: 'Celebrate the year-end with the team.',
		date: '2024-12-20',
		time: '18:00',
		location: 'Party Hall',
		type: 'meeting',
	},
	{
		id: 12,
		title: 'Webinar: Cloud Computing',
		description: 'Latest trends in cloud technologies.',
		date: '2025-01-03',
		time: '15:00',
		location: 'Online',
		type: 'webinar',
	},
	{
		id: 13,
		title: 'Strategy Meeting',
		description: 'Discuss strategy for the next quarter.',
		date: '2025-01-10',
		time: '11:00',
		location: 'Conference Room B',
		type: 'meeting',
	},
	{
		id: 14,
		title: 'QA Training',
		description: 'Train new QA team members.',
		date: '2025-01-15',
		time: '09:00',
		location: 'Training Room',
		type: 'qa',
	},
	{
		id: 15,
		title: 'Tech Conference',
		description: 'Annual technology conference.',
		date: '2025-01-20',
		time: '09:00',
		location: 'Tech Park',
		type: 'conference',
	},
	{
		id: 16,
		title: 'Webinar: Security Best Practices',
		description: 'Learn about security in applications.',
		date: '2025-01-25',
		time: '14:00',
		location: 'Online',
		type: 'webinar',
	},
	{
		id: 17,
		title: 'Project Review',
		description: 'Review project milestones with team.',
		date: '2025-02-01',
		time: '10:00',
		location: 'Room 303',
		type: 'meeting',
	},
	{
		id: 18,
		title: 'Product Launch',
		description: 'Launch new product features.',
		date: '2025-02-10',
		time: '13:00',
		location: 'Main Hall',
		type: 'meeting',
	},
	{
		id: 19,
		title: 'Annual QA Conference',
		description: 'Discuss the latest in QA.',
		date: '2025-02-15',
		time: '09:00',
		location: 'Convention Center',
		type: 'qa',
	},
	{
		id: 20,
		title: 'Webinar: Agile Methodologies',
		description: 'Understanding Agile practices.',
		date: '2025-02-20',
		time: '11:00',
		location: 'Online',
		type: 'webinar',
	},
	{
		id: 21,
		title: 'Sprint Planning',
		description: 'Plan for the upcoming sprint.',
		date: '2025-03-01',
		time: '10:00',
		location: 'Room 201',
		type: 'meeting',
	},
	{
		id: 22,
		title: 'Feedback Session',
		description: 'Gather feedback on recent changes.',
		date: '2025-03-05',
		time: '14:00',
		location: 'Room 102',
		type: 'meeting',
	},
	{
		id: 23,
		title: 'Webinar: Data Analysis',
		description: 'Learn data analysis techniques.',
		date: '2025-03-10',
		time: '16:00',
		location: 'Online',
		type: 'webinar',
	},
	{
		id: 24,
		title: 'Quarterly Review',
		description: 'Review quarterly performance.',
		date: '2025-03-15',
		time: '09:00',
		location: 'Conference Room A',
		type: 'conference',
	},
	{
		id: 25,
		title: 'Networking Event',
		description: 'Network with industry professionals.',
		date: '2025-03-20',
		time: '18:00',
		location: 'City Hall',
		type: 'meeting',
	},
	{
		id: 26,
		title: 'Workshop: Effective Communication',
		description: 'Enhance communication skills.',
		date: '2025-03-25',
		time: '10:00',
		location: 'Training Room',
		type: 'webinar',
	},
	{
		id: 27,
		title: 'Product Feedback Meeting',
		description: 'Gather feedback on product features.',
		date: '2025-04-01',
		time: '11:00',
		location: 'Room 201',
		type: 'meeting',
	},
	{
		id: 28,
		title: 'QA Retrospective',
		description: 'Discuss past QA processes and improvements.',
		date: '2025-04-05',
		time: '14:00',
		location: 'Zoom',
		type: 'qa',
	},
	{
		id: 29,
		title: 'Webinar: Future of Tech',
		description: 'Discuss future trends in technology.',
		date: '2025-04-10',
		time: '16:00',
		location: 'Online',
		type: 'webinar',
	},
	{
		id: 30,
		title: 'Team Building Activity',
		description: 'Engage in team-building exercises.',
		date: '2025-04-15',
		time: '13:00',
		location: 'Park',
		type: 'meeting',
	},
	{
		id: 31,
		title: 'Company Retreat',
		description: 'Annual company retreat to build team spirit.',
		date: '2025-04-20',
		time: '09:00',
		location: 'Resort',
		type: 'meeting',
	},
	{
		id: 32,
		title: 'Webinar: Best Coding Practices',
		description: 'Learn best practices in coding.',
		date: '2025-05-01',
		time: '11:00',
		location: 'Online',
		type: 'webinar',
	},
	{
		id: 33,
		title: 'Sales Strategy Meeting',
		description: 'Discuss sales strategies for next quarter.',
		date: '2025-05-05',
		time: '10:00',
		location: 'Room 302',
		type: 'meeting',
	},
	{
		id: 34,
		title: 'Marketing Conference',
		description: 'Annual marketing strategies conference.',
		date: '2025-05-10',
		time: '09:00',
		location: 'Conference Center',
		type: 'conference',
	},
	{
		id: 35,
		title: 'Webinar: Introduction to Python',
		description: 'Learn the basics of Python programming.',
		date: '2025-05-15',
		time: '14:00',
		location: 'Online',
		type: 'webinar',
	},
	{
		id: 36,
		title: 'Team Performance Review',
		description: 'Review team performance and set goals.',
		date: '2025-05-20',
		time: '13:00',
		location: 'Room 101',
		type: 'meeting',
	},
	{
		id: 37,
		title: 'End-of-Quarter Review',
		description: 'Review performance at the end of the quarter.',
		date: '2025-06-01',
		time: '09:00',
		location: 'Main Hall',
		type: 'conference',
	},
	{
		id: 38,
		title: 'Webinar: Building REST APIs',
		description: 'Learn how to build RESTful APIs.',
		date: '2025-06-05',
		time: '16:00',
		location: 'Online',
		type: 'webinar',
	},
	{
		id: 39,
		title: 'Sprint Review Meeting',
		description: 'Review outcomes of the sprint.',
		date: '2025-06-10',
		time: '11:00',
		location: 'Room 303',
		type: 'meeting',
	},
	{
		id: 40,
		title: 'Company All Hands',
		description: 'Gather everyone for an all-hands meeting.',
		date: '2025-06-15',
		time: '13:00',
		location: 'Main Hall',
		type: 'meeting',
	},
	{
		id: 41,
		title: 'Kickoff Meeting',
		description: 'Kickoff for the new marketing campaign.',
		date: '2024-11-01',
		time: '09:00',
		location: 'Room 105',
		type: 'meeting',
	},
	{
		id: 42,
		title: 'QA Testing Session',
		description: 'Test new features before the release.',
		date: '2024-11-01',
		time: '14:00',
		location: 'Lab 2',
		type: 'qa',
	},
	{
		id: 43,
		title: 'Weekly Sync',
		description: 'Sync up with the team on current tasks.',
		date: '2024-11-01',
		time: '16:00',
		location: 'Zoom',
		type: 'meeting',
	},

	{
		id: 44,
		title: 'Client Conference Call',
		description: 'Discuss project updates with the client.',
		date: '2024-11-02',
		time: '10:00',
		location: 'Zoom',
		type: 'conference',
	},
	{
		id: 45,
		title: 'Team Outing',
		description: 'Fun day out with the team.',
		date: '2024-11-02',
		time: '13:00',
		location: 'Local Park',
		type: 'meeting',
	},

	{
		id: 46,
		title: 'Monthly Review',
		description: 'Review performance metrics from last month.',
		date: '2024-11-05',
		time: '11:00',
		location: 'Room 201',
		type: 'meeting',
	},
	{
		id: 47,
		title: 'Webinar: Digital Marketing',
		description: 'Insights into effective digital marketing strategies.',
		date: '2024-11-05',
		time: '15:00',
		location: 'Online',
		type: 'webinar',
	},

	{
		id: 48,
		title: 'Product Development Meeting',
		description: 'Discuss product roadmap for the upcoming quarter.',
		date: '2024-11-06',
		time: '10:00',
		location: 'Conference Room A',
		type: 'meeting',
	},
	{
		id: 49,
		title: 'Sales Strategy Session',
		description: 'Plan sales tactics for next quarter.',
		date: '2024-11-06',
		time: '14:00',
		location: 'Room 102',
		type: 'meeting',
	},

	{
		id: 50,
		title: 'Webinar: Financial Planning',
		description: 'Learn about financial strategies for startups.',
		date: '2024-11-08',
		time: '16:00',
		location: 'Online',
		type: 'webinar',
	},

	{
		id: 51,
		title: 'All-Hands Meeting',
		description: 'Company-wide meeting to discuss updates.',
		date: '2024-11-10',
		time: '09:00',
		location: 'Main Hall',
		type: 'meeting',
	},
	{
		id: 52,
		title: 'Networking Event',
		description: 'Meet and connect with industry peers.',
		date: '2024-11-10',
		time: '17:00',
		location: 'Downtown Hotel',
		type: 'meeting',
	},

	{
		id: 53,
		title: 'Monthly Dev Meeting',
		description: 'Discussion on development progress and issues.',
		date: '2024-11-12',
		time: '10:00',
		location: 'Room 201',
		type: 'meeting',
	},
	{
		id: 54,
		title: 'Webinar: Cybersecurity Basics',
		description: 'Introduction to cybersecurity for businesses.',
		date: '2024-11-12',
		time: '15:00',
		location: 'Online',
		type: 'webinar',
	},

	{
		id: 55,
		title: 'Design Review',
		description: 'Review design mockups for the new product.',
		date: '2024-11-15',
		time: '11:00',
		location: 'Design Studio',
		type: 'meeting',
	},
	{
		id: 56,
		title: 'Training: Effective Leadership',
		description: 'Workshop on leadership skills.',
		date: '2024-11-15',
		time: '14:00',
		location: 'Room 303',
		type: 'qa',
	},

	{
		id: 57,
		title: 'Webinar: Content Creation',
		description: 'Best practices for content marketing.',
		date: '2024-11-17',
		time: '10:00',
		location: 'Online',
		type: 'webinar',
	},

	{
		id: 58,
		title: 'Team Building Exercise',
		description: 'Engage in activities to strengthen team dynamics.',
		date: '2024-11-20',
		time: '09:00',
		location: 'Local Park',
		type: 'meeting',
	},
	{
		id: 59,
		title: 'Sprint Planning Meeting',
		description: 'Plan tasks for the upcoming sprint.',
		date: '2024-11-20',
		time: '13:00',
		location: 'Room 102',
		type: 'meeting',
	},

	{
		id: 60,
		title: 'Quarterly Planning',
		description: 'Prepare for the next quarter’s goals.',
		date: '2024-11-25',
		time: '10:00',
		location: 'Room 301',
		type: 'meeting',
	},
	{
		id: 61,
		title: 'Webinar: AI in Business',
		description: 'Exploring AI applications in business.',
		date: '2024-11-25',
		time: '15:00',
		location: 'Online',
		type: 'webinar',
	},

	{
		id: 62,
		title: 'End of Year Review',
		description: 'Discuss performance and outcomes of the year.',
		date: '2024-12-01',
		time: '10:00',
		location: 'Main Hall',
		type: 'conference',
	},
	{
		id: 63,
		title: 'Company Holiday Party',
		description: 'Celebrate the year with a holiday party.',
		date: '2024-12-20',
		time: '19:00',
		location: 'Party Hall',
		type: 'meeting',
	},

	{
		id: 64,
		title: 'New Year Strategy Session',
		description: 'Plan strategies for the new year.',
		date: '2025-01-05',
		time: '11:00',
		location: 'Room 201',
		type: 'meeting',
	},
	{
		id: 65,
		title: 'Webinar: Leadership Skills',
		description: 'Enhance your leadership capabilities.',
		date: '2025-01-05',
		time: '15:00',
		location: 'Online',
		type: 'webinar',
	},

	{
		id: 66,
		title: 'Kickoff for New Project',
		description: 'Kickoff meeting for the new project.',
		date: '2025-01-10',
		time: '10:00',
		location: 'Room 101',
		type: 'meeting',
	},
	{
		id: 67,
		title: 'QA Process Training',
		description: 'Train on the new QA process.',
		date: '2025-01-10',
		time: '14:00',
		location: 'Lab 2',
		type: 'qa',
	},

	{
		id: 68,
		title: 'Webinar: Market Trends',
		description: 'Discuss trends in the market.',
		date: '2025-01-15',
		time: '16:00',
		location: 'Online',
		type: 'webinar',
	},

	{
		id: 69,
		title: 'Feedback Meeting',
		description: 'Gather feedback from the team on processes.',
		date: '2025-01-20',
		time: '11:00',
		location: 'Room 202',
		type: 'meeting',
	},
	{
		id: 70,
		title: 'Strategy Review',
		description: 'Review and adjust the company strategy.',
		date: '2025-01-20',
		time: '14:00',
		location: 'Main Hall',
		type: 'meeting',
	},

	{
		id: 71,
		title: 'Webinar: Remote Work Strategies',
		description: 'Best practices for remote work.',
		date: '2025-01-25',
		time: '10:00',
		location: 'Online',
		type: 'webinar',
	},

	{
		id: 72,
		title: 'End-of-Month Review',
		description: 'Review performance at the end of the month.',
		date: '2025-02-01',
		time: '10:00',
		location: 'Room 301',
		type: 'meeting',
	},
	{
		id: 73,
		title: 'Webinar: Business Analytics',
		description: 'Understand business analytics.',
		date: '2025-02-01',
		time: '15:00',
		location: 'Online',
		type: 'webinar',
	},

	{
		id: 74,
		title: 'Team Planning Session',
		description: 'Plan the upcoming project tasks.',
		date: '2025-02-05',
		time: '09:00',
		location: 'Room 105',
		type: 'meeting',
	},
	{
		id: 75,
		title: 'Conference on Innovation',
		description: 'Annual conference on innovation.',
		date: '2025-02-05',
		time: '14:00',
		location: 'Convention Center',
		type: 'conference',
	},

	{
		id: 76,
		title: 'Webinar: Effective Negotiation',
		description: 'Learn negotiation skills for business.',
		date: '2025-02-10',
		time: '11:00',
		location: 'Online',
		type: 'webinar',
	},
	{
		id: 77,
		title: 'Project Closure Meeting',
		description: 'Discuss project closure and final outcomes.',
		date: '2025-02-15',
		time: '10:00',
		location: 'Room 301',
		type: 'meeting',
	},

	{
		id: 78,
		title: 'QA Review Meeting',
		description: 'Review QA results from the project.',
		date: '2025-02-20',
		time: '13:00',
		location: 'Lab 1',
		type: 'qa',
	},
	{
		id: 79,
		title: 'Webinar: Stress Management',
		description: 'Tips and strategies for managing stress.',
		date: '2025-02-20',
		time: '16:00',
		location: 'Online',
		type: 'webinar',
	},

	{
		id: 80,
		title: 'Budget Planning Meeting',
		description: 'Discuss the budget for the upcoming year.',
		date: '2025-02-28',
		time: '11:00',
		location: 'Room 202',
		type: 'meeting',
	},
];
